config/routes.rb
Rails.application.routes.draw do
  resources :extensions
  resources :hives
  resources :apiaries
  # get 'dashboard/index' as :dashboard
  post 'extensions/set_state' , to: 'extensions#set_state'
  devise_for :users
  root to: "dashboard#index"
end

app/models/apiary.rb
class Apiary < ActiveRecord::Base
	belongs_to :user
	has_many :hives, :dependent => :destroy
end

app/controllers/apiaries_controller.rb
class ApiariesController < ApplicationController
  before_action :set_apiary, only: [:show, :edit, :update, :destroy]

  # GET /apiaries
  # GET /apiaries.json
  def index
    # Show apiaries only for the current user
    @apiaries = Apiary.where(user_id:current_user.id)
  end

  # GET /apiaries/1
  # GET /apiaries/1.json
  def show
  end

  # GET /apiaries/new
  def new
    @apiary = Apiary.new
  end

  # GET /apiaries/1/edit
  def edit
    @apiary = Apiary.find(params[:id])
    if @apiary.user_id != current_user.id
      redirect_to apiaries_path
    end
  end

  # POST /apiaries
  # POST /apiaries.json
  def create
    @apiary = Apiary.new(apiary_params)
    respond_to do |format|
      if @apiary.save
        format.html { redirect_to apiaries_path, notice: 'Apiary was successfully created.' }
        format.json { render :new, status: :created, location: @apiary }
      else
        format.html { render :new }
        format.json { render json: @apiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apiaries/1
  # PATCH/PUT /apiaries/1.json
  def update
    respond_to do |format|
      if @apiary.update(apiary_params)
        format.html { redirect_to @apiary, notice: 'Apiary was successfully updated.' }
        format.json { render :show, status: :ok, location: @apiary }
      else
        format.html { render :edit }
        format.json { render json: @apiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apiaries/1
  # DELETE /apiaries/1.json
  def destroy
    @apiary.destroy
    respond_to do |format|
      format.html { redirect_to apiaries_url, notice: 'Apiary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apiary
      @apiary = Apiary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apiary_params
      params.require(:apiary).permit(:name, :lon, :lat, :hive_type, :user_id)
    end
end

app/helpers/apiaries_helper.rb
module ApiariesHelper
end

app/views/apiaries/_extension.html.erb
<div class="extension <%= extension.state %>" data-toggle="popover" title="Edit extension" data-state="<%= extension.state %>" data-extension-id="<%= extension.id %>">
	<div class="center-extension">
	<% extension.frames.each do |frame|%>
		<div class="frame type-<%= frame.frame_type %>" data-id="<%= frame.id %>"></div>
	<% end %>
	</div>
</div>

app/views/apiaries/_form.html.erb
<%= form_for(@apiary) do |f| %>
  <% if @apiary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apiary.errors.count, "error") %> prohibited this apiary from being saved:</h2>

      <ul>
      <% @apiary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Longitude' %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label 'Latitude' %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :hive_type %><br>
    <%= f.text_field :hive_type %>
  </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apiaries/_hive.html.erb
<div class="hive col-lg-2">
	<div class="extensions col-lg-12 padding-none">
		<% hive.extensions.each do |extension|%>
		<%= render 'extension', extension:extension %>
		<% end %>
	</div>
	<div class="hive-number"><%= hive.number %></div>
	<%= form_tag('/extensions', remote: true, method: 'create') do %>
		<%= hidden_field_tag 'extension[hive_id]', hive.id %>
		<% tempStyle = hive.extensions.count < 3 ? '' : 'display:none' %>
		<%= link_to "", 'javascript:void(0)', class: "add_extension glyphicon glyphicon-plus", style: tempStyle %>
	<% end %> 
</div>

app/views/apiaries/edit.html.erb
<h1>Editing Apiary</h1>

<%= render 'form' %>

<%= link_to 'Show', @apiary %> |
<%= link_to 'Back', apiaries_path %>

app/views/apiaries/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<% @apiaries.each do |apiary| %>
	<div class="row">
		<div class="apiary-header">
			<h2>
				<%= apiary.name %>
			</h2>
			<%= link_to 'Edit', edit_apiary_path(apiary), class: 'btn btn-primary' %>
			<%= link_to 'Destroy', apiary, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
		</div>
		
		<p>Location:</p>
		<div id="map"></div>
   		<% if apiary.hives %>
   		<div class="hives">
   			<div class="scrollable">
			<% apiary.hives.each do |hive| %>
				<%= render 'hive', hive:hive %>
			<% end %>
			</div>
		</div>
	</div>
	<% end %>
 </div>
 <% end %>
<!-- <script async defer
//         src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFYK-bGfNzEBwEc0zXf1tXxEmjnQrFW7g&callback=initMap"></script>
<br> -->
<div class="row mt-10">
	<%= link_to 'New Apiary', new_apiary_path, class: 'btn btn-primary' %>
	<%= link_to 'New Hive', new_hive_path, class: 'btn btn-primary' %>
</div>

app/views/apiaries/new.html.erb
<h1>New Apiary</h1>

<%= render 'form' %>

<%= link_to 'Back', apiaries_path %>

app/views/apiaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @apiary.name %>
</p>

<p>
  <strong>Location:</strong>
  Longtitude:<%= @apiary.lon %><br>
  Latitude:<%= @apiary.lat %>
</p>

<p>
  <strong>Hive type:</strong>
  <%= @apiary.hive_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @apiary.user_id %>
</p>

<%= link_to 'Edit', edit_apiary_path(@apiary) %> |
<%= link_to 'Back', apiaries_path %>