config/routes.rb
Rails.application.routes.draw do
  resources :extensions
  resources :hives
  resources :apiaries
  # get 'dashboard/index' as :dashboard
  post 'extensions/set_state' , to: 'extensions#set_state'
  devise_for :users
  root to: "dashboard#index"
end

app/models/extension.rb
class Extension < ActiveRecord::Base
	belongs_to :hive
	has_many :frames, :dependent => :destroy
end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
  before_action :set_extension, only: [:show, :edit, :update, :destroy]

  # GET /extensions
  # GET /extensions.json
  def index
    @extensions = Extension.all
  end

  # GET /extensions/1
  # GET /extensions/1.json
  def show

  end

  # GET /extensions/new
  def new
    @extension = Extension.new
  end

  # GET /extensions/1/edit
  def edit
  end

  # POST /extensions
  # POST /extensions.json
  def create
    params = extension_params
    @extension = Extension.new(extension_params)
    respond_to do |format|
      if @extension.save
        @frames = Frame.create(empty_frames_array @extension)
        format.html { redirect_to @extension, notice: 'Extension was successfully created.' }
        format.json { render :show, status: :created, location: @extension }
      else
        format.html { render :new }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_state
    params = set_state_params
    @extension = Extension.find(params['id'])
      respond_to do |format|
      if @extension.update(:state => params['state'])
        format.json { render :show, status: :ok, location: @extension }
      else
        format.json { render json: @extension.errors, status: 'Error changing state' }
      end
    end
    # Rails.logger.debug params
    # @extension = Extension.find(params.extension.hive_id);
    # @extension.state = params.
  end
  # PATCH/PUT /extensions/1
  # PATCH/PUT /extensions/1.json
  def update
    respond_to do |format|
      if @extension.update(extension_params)
        format.html { redirect_to @extension, notice: 'Extension was successfully updated.' }
        format.json { render :show, status: :ok, location: @extension }
      else
        format.html { render :edit }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extensions/1
  # DELETE /extensions/1.json
  def destroy
    @extension.destroy
    respond_to do |format|
      format.html { redirect_to extensions_url, notice: 'Extension was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extension
      @extension = Extension.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # Add order id for hive if you want to reorder them
    def extension_params
      params.require(:extension).permit(:hive_id, :state)
    end
    
    def set_state_params
      params.require(:extension).permit(:id, :state)
    end
    # Create default array with 8 empty frames
    # TODO: Change number of empty frames based on type of the hive
    def empty_frames_array(extension)
      default_frames = Array.new
      (0..7).each do |i|
         default_frames.push({:frame_type => "empty",:extension_id => extension.id })
      end
      default_frames
    end
end

app/helpers/extensions_helper.rb
module ExtensionsHelper
end

app/views/extensions/_form.html.erb
<%= form_for(@extension) do |f| %>
  <% if @extension.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@extension.errors.count, "error") %> prohibited this extension from being saved:</h2>

      <ul>
      <% @extension.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :hive_id %><br>
    <%= f.number_field :hive_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/extensions/edit.html.erb
<h1>Editing Extension</h1>

<%= render 'form' %>

<%= link_to 'Show', @extension %> |
<%= link_to 'Back', extensions_path %>

app/views/extensions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Extensions</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Apiary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extensions.each do |extension| %>
      <tr>
        <td><%= extension.order_id %></td>
        <td><%= extension.hive_id %></td>
        <td><%= link_to 'Show', extension %></td>
        <td><%= link_to 'Edit', edit_extension_path(extension) %></td>
        <td><%= link_to 'Destroy', extension, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<img src="./images/spiner.gif"/>
<br>

<%= link_to 'New Extension', new_extension_path %>

app/views/extensions/new.html.erb
<h1>New Extension</h1>

<%= render 'form' %>

<%= link_to 'Back', extensions_path %>

app/views/extensions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @extension.order_id %>
</p>

<p>
  <strong>hive_id:</strong>
  <%= @extension.hive_id %>
</p>

<%= link_to 'Edit', edit_extension_path(@extension) %> |
<%= link_to 'Back', extensions_path %>