config/routes.rb
Rails.application.routes.draw do
  resources :extensions
  resources :hives
  resources :apiaries
  # get 'dashboard/index' as :dashboard
  post 'extensions/set_state' , to: 'extensions#set_state'
  devise_for :users
  root to: "dashboard#index"
end

app/models/hive.rb
class Hive < ActiveRecord::Base
	belongs_to :apiary
	has_many :extensions, :dependent => :destroy
	def self.hive_types
		['RV','FR8','FR10']
	end
end

app/controllers/hives_controller.rb
class HivesController < ApplicationController
  before_action :set_hive, only: [:show, :edit, :update, :destroy]

  # GET /hives
  # GET /hives.json
  def index
    @hives = Hive.all
  end

  # GET /hives/1
  # GET /hives/1.json
  def show
  end

  # GET /hives/new
  def new
    @hive = Hive.new
    @apiaries = Apiary.where(user_id:current_user.id)
  end

  # GET /hives/1/edit
  def edit
    @apiaries = Apiary.where(user_id:current_user.id)
  end

  # POST /hives
  # POST /hives.json
  def create
    @hive = Hive.new(hive_params)

    respond_to do |format|
      if @hive.save
        format.html { redirect_to apiaries_path, notice: 'Hive was successfully created.' }
        format.json { render :show, status: :created, location: @hive }
      else
        format.html { render :new }
        format.json { render json: @hive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hives/1
  # PATCH/PUT /hives/1.json
  def update
    respond_to do |format|
      if @hive.update(hive_params)
        format.html { redirect_to @hive, notice: 'Hive was successfully updated.' }
        format.json { render :show, status: :ok, location: @hive }
      else
        format.html { render :edit }
        format.json { render json: @hive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hives/1
  # DELETE /hives/1.json
  def destroy
    @hive.destroy
    respond_to do |format|
      format.html { redirect_to hives_url, notice: 'Hive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hive
      @hive = Hive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hive_params
      params.require(:hive).permit(:number, :hive_type, :apiary_id, :order_id)
    end
end

app/helpers/hives_helper.rb
module HivesHelper
	# Return true if value is selected
	def is_selected current_value, passed_value
		current_value.eql? passed_value
	end
end

app/views/hives/_form.html.erb
<%= form_for(@hive) do |f| %>
  <% if @hive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hive.errors.count, "error") %> prohibited this hive from being saved:</h2>

      <ul>
      <% @hive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :hive_type %><br>
    <%= f.select(:hive_type) do %>
      <% Hive.hive_types.each do |hive_type| -%>
        <%= content_tag(:option, hive_type, value: hive_type, selected: is_selected(hive_type, @hive.hive_type)) %>
      <% end %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :apiary_id %><br>
    <%= f.select(:apiary_id) do %>
      <% @apiaries.each do |apiary| -%>
        <%= content_tag(:option, apiary.name, value: apiary.id) %>
      <% end %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hives/edit.html.erb
<h1>Editing Hive</h1>

<%= render 'form' %>

<%= link_to 'Show', @hive %> |
<%= link_to 'Back', hives_path %>

app/views/hives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hives</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Hive Type</th>
      <th>Apiary</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hives.each do |hive| %>
      <tr>
        <td><%= hive.number %></td>
        <td><%= hive.hive_type %></td>
        <td><%= hive.apiary_id %></td>
        <td><%= hive.order_id %></td>
        <td><%= link_to 'Show', hive %></td>
        <td><%= link_to 'Edit', edit_hive_path(hive) %></td>
        <td><%= link_to 'Destroy', hive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hive', new_hive_path %>

app/views/hives/new.html.erb
<h1>New Hive</h1>

<%= render 'form' %>

<%= link_to 'Back', hives_path %>

app/views/hives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @hive.number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @hive.hive_type %>
</p>

<p>
  <strong>Apirary:</strong>
  <%= @hive.apiary_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @hive.order_id %>
</p>

<%= link_to 'Edit', edit_hive_path(@hive) %> |
<%= link_to 'Back', hives_path %>