config/routes.rb
Rails.application.routes.draw do
  resources :extensions
  resources :hives
  resources :apiaries
  # get 'dashboard/index' as :dashboard
  post 'extensions/set_state' , to: 'extensions#set_state'
  devise_for :users
  root to: "dashboard#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kosnice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>
</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Pcelinjaci</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
					<% if current_user %>
					<li>
					    <a href="#">Logged in as <%= current_user.email %></a>
					</li>
					<li>
					    <%= link_to "Apiaries", apiaries_path %>
					</li>
					<li>
					    <%= link_to "Log out", destroy_user_session_path, :method => 'delete' %>
					</li>
					<% else %>
					<li>
					    <%= link_to "Sign up", new_user_registration_path %>
					</li>
					<li>
					    <%= link_to "Log in", new_user_session_path %>
					</li>
					<% end %>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
    	<div class="row">
    		<%= render partial: "shared/flash_messages", flash: flash %> 
    	</div>
        <div class="row">
            <div class="col-lg-12">
                <%= yield %>
            </div>
        </div>
        <!-- /.row -->

    </div>
</body>
</html>